fun main() {

    val str = getNumber("10.5") // int로 변환할 수 없는 실수 문자열
    println(str)
    throwException();
}

fun getNumber(str: String): Int {
    return try {
        Integer.parseInt(str)

    } catch (e: Exception) {
        0
    } finally {
        println("exception이 나던 안나던 무조건 실행되는 코드")
    }
}

fun throwException() {
    try {
        println("throw ArithmeticException")
        throw ArithmeticException("under int") // 예외 강제 발생
    } catch (e: ArithmeticException) { // 발생
        println("e.message : " + e.message)
    } catch (e2: Exception) {
        println("Exception")
    }
}